# SPDX-FileCopyrightText: 2024 Jasem Mutlaq <mutlaqja@ikarustech.com>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kstars
version: 3.7.2
confinement: classic
base: core22
compression: lzo
adopt-info: kstars

apps:
    kstars:
        extensions:
        - kde-neon-5
        common-id: org.kde.kstars.desktop
        desktop: usr/share/applications/org.kde.kstars.desktop
        command: usr/bin/kstars
        plugs:
        - home
        - opengl
        - network
        - network-bind
        - unity7
        - joystick
        - pulseaudio
        - serial-port
        - camera
        - gpio
        - gpio-control
        - location-observe
        - hardware-observe
        - hidraw
        - i2c
        - password-manager-service
        - location-control
        - location-observe
        - raw-usb
        - desktop
        command-chain:
        - snap/command-chain/desktop-launch5
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.kstars
        bus: session
parts:
    kstars:
        parse-info:
        - usr/share/metainfo/org.kde.kstars.appdata.xml
        plugin: cmake
        cmake-parameters:
        - -DCMAKE_INSTALL_PREFIX=/usr
        - -DCMAKE_BUILD_TYPE=Release
        - -DENABLE_TESTING=OFF
        - -DBUILD_TESTING=OFF
        - -DBUILD_DOC=OFF
        - -DKDE_SKIP_TEST_SETTINGS=ON
        build-packages:
        - qt5-default
        - libeigen3-dev
        - zlib1g-dev
        - libcfitsio-dev
        - libnova-dev
        - libgsl-dev
        - libindi-dev
        - qt5keychain-dev
        - wcslib-dev
        stage-packages:
        - astrometry.net
        - indi-bin
        - indi-full
        - xplanet
        - libcfitsio5
        - libnova-0.16-0
        - libgsl27
        - libpgsbox7
        - libwcs7
        - libqt5keychain1
        source: https://anongit.kde.org/kstars.git
